spring.application.name=server_fullStack
sever.port=8083
spring.datasource.url=
spring.datasource.username=root
spring.datasource.password=Nandhu07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true